### ISSUE TITLE
Feature request: Way to email selected group on the waitlist

### ISSUE THREAD

**Issue by sweirich** [upenn/cis-waitlist-issues#10]
Thanks for setting up this system, Joe! It is way better than the previous version. 

However, I didn't see a way to easily access the email address of students who are currently on the waitlist so that I can provide general status updates. Is there a way to do so that I've missed?

**Comment by devietti** [comment]
Sure, I added a button that will copy the email addresses of all selected students to the clipboard. Does this sound good?

**Comment by sweirich** [comment]
Thanks!
