### ISSUE TITLE
Not accepted to CIS3800 waitlist

### ISSUE THREAD

**Issue by nathanmbaker10** [upenn/cis-waitlist-issues#11]
No place to put input. Maybe there are no questions?
<img width="1208" alt="Screen Shot 2022-08-13 at 4 58 00 PM" src="https://user-images.githubusercontent.com/16793701/184517153-a1658497-652b-4f70-a5ae-0a5f1fd17642.png">

Error message when clicking submit.
<img width="812" alt="Screen Shot 2022-08-13 at 4 59 51 PM" src="https://user-images.githubusercontent.com/16793701/184517198-e7a2c9ef-20e6-49e1-860a-d03cb7de6b19.png">

**Comment by devietti** [comment]
Yeah, this was a bug where the site thought you had to fill out questions for CIS 3800 but then there weren't any questions to fill out, doh! It should work fine now, your request is *under instructor review* now.
