### ISSUE TITLE
Student input error for CIS 8000-002

### ISSUE THREAD

**Issue by Adalw1n** [upenn/cis-waitlist-issues#13]
For CIS 8000-002 waitlist, it seems that there are no questions provided and it gives me an error similar to the issue #11. Could you check it out please? Thank you.

![1](https://user-images.githubusercontent.com/91153561/187358027-bb32ef32-b950-4e7f-8be1-aabd5e0ece7c.jpg)
![2](https://user-images.githubusercontent.com/91153561/187358028-a15e9e8b-ea88-4942-9859-efc110c9a4fe.jpg)

**Comment by devietti** [comment]
Ah, yeah, sorry about that, there's a little bug with creating new course waitlists. This has been fixed for CIS 8000-002 now.
