### ISSUE TITLE
Cannot open the website

### ISSUE THREAD

**Issue by nbxszby416** [upenn/cis-waitlist-issues#14]
Hi, I cannot open these two websites now:
1. https://waitlist.cis.upenn.edu/
2. https://advising.cis.upenn.edu/waitlist/

Could you please check it? Thank you so much!!

**Comment by devietti** [comment]
Sorry about this, there is CETS scheduled maintenance occurring on the webserver that runs these sites (and forms.cis.upenn.edu as well). They should be back up later this morning.

**Comment by devietti** [comment]
Just fyi, these websites are back online now!
