### ISSUE TITLE
Waitlisty reports NaN years ago for Path sync

### ISSUE THREAD

**Issue by anli5005** [upenn/cis-waitlist-issues#16]
Our newly created Waitlisty for CIS 1951 (section 201) reports that the last Path sync happened NaN years ago:

<img width="1323" alt="Waitlisty reporting NaN years ago" src="https://github.com/upenn/waitlisty-issues/assets/7005789/a2c89110-0d37-49dc-a28a-eafb28d5a566">

This may be related to our course having just been added to Path, but it does lead to some confusing verbiage nonetheless.

**Comment by JHawk0224** [comment]
👀

**Comment by fyy26** [comment]
⏰ 👀

**Comment by devietti** [comment]
Thank you for reporting this! I've fixed this now; it was indeed because the "last Path sync" is null if it hasn't happened yet. Now the text will only show once the first Path sync has occurred.
