### ISSUE TITLE
Unable to withdraw course permit requests - "Unauthorized" 

### ISSUE THREAD

**Issue by fyy26** [upenn/cis-waitlist-issues#17]
https://github.com/upenn/waitlisty-issues/assets/54198723/3e82f149-7ab5-4943-9ede-a4c85c800b3b

**Comment by devietti** [comment]
Thanks for reporting this, and sorry it sat for so long. The bug here is that minicourse instructors aren't allowed to withdraw a course request; they end up with "instructor" permissions which doesn't allow this. I'll think about how our permission checks could be reworked.

**Comment by devietti** [comment]
This has been fixed now!

**Comment by fyy26** [comment]
that's such an edge case! tysm for fixing it :)))
