### ISSUE TITLE
Import Answers Into Waitlisty from Google Forms doesn't work

### ISSUE THREAD

**Issue by sammjung** [upenn/cis-waitlist-issues#18]
The video shows the issue described (look at the end time 1:35ish).

https://github.com/upenn/waitlisty-issues/assets/74062875/35995679-12b8-4772-9cfe-99b1efcafd25

**Comment by minfeishen2024** [comment]
Having the same issue, my error message: 

An error occurred "Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"

**Comment by devietti** [comment]
This seems to be working better now, I believe your answers have been imported! I think this was due to slow responses from the Google Forms API that were timing out. If you continue to have issues, feel free to reopen.

**Comment by sammjung** [comment]
Also, I accidentally withdrew my permission request for a course (cis 550),
and it won't let me resubmit another one. Who should I contact to fix this?

Thank you,
Sam

**Comment by devietti** [comment]
Ok, I can follow-up separately about that.

**Comment by hetankevin** [comment]
Having a similar issue here, except that when I click on the green import button, nothing happens.

**Comment by devietti** [comment]
@hetankevin could you please email me with your PennKey and the course you're having trouble with? Thanks!
