### ISSUE TITLE
When clicking on "My Forms"... It bugs

### ISSUE THREAD

**Issue by fyy26** [upenn/cis-waitlist-issues#20]
<img width="731" alt="image" src="https://github.com/user-attachments/assets/c04bb670-ce84-4869-954b-fa12283b17c2">

**Comment by fyy26** [comment]
<img width="582" alt="image" src="https://github.com/user-attachments/assets/7802a3b6-309b-41aa-acb5-b36e8a5f43b5">

**Comment by devietti** [comment]
Indeed, this link is inaccessible to students and shouldn't be rendered. I've removed it now. You can use the other "my forms" button above it to access student forms.
