### ISSUE TITLE
Unable to answer CIS5450 waitlist questions

### ISSUE THREAD

**Issue by gbioteau** [upenn/cis-waitlist-issues#5]
I can't enter any info for the CIS 5450 waitlist.
![image](https://user-images.githubusercontent.com/108839135/177652419-806e3e5d-a9bc-4721-a440-c33137a24a36.png)

**Comment by devietti** [comment]
Sorry about that, there was an issue with importing PRs from Path. It has been resolved now, so you should be able to answer these questions now.
