### ISSUE TITLE
Unable to answer CIS 5450, 4500, and 5210 Questions

### ISSUE THREAD

**Issue by erictnwang** [upenn/cis-waitlist-issues#6]
<img width="898" alt="Screen Shot 2022-07-06 at 6 25 14 PM" src="https://user-images.githubusercontent.com/91151359/177670402-9b7ed4a2-fdc8-4b97-9cf0-006b569ab967.png">
<img width="981" alt="Screen Shot 2022-07-06 at 6 25 30 PM" src="https://user-images.githubusercontent.com/91151359/177670439-bb21c35f-6cd4-4605-9d1b-d648b8466858.png">
<img width="1012" alt="Screen Shot 2022-07-06 at 6 25 41 PM" src="https://user-images.githubusercontent.com/91151359/177670456-e7f6e23f-76cf-4821-8a69-c0891b6520ff.png">

**Comment by devietti** [comment]
Sorry about that, there was an issue with importing PRs from Path. It has been resolved now, so you should be able to answer these questions now. Same root cause as #5.
