### ISSUE TITLE
Unable to answer CIS 505 & 521 Waitlist Questions

### ISSUE THREAD

**Issue by cywudats** [upenn/cis-waitlist-issues#7]
I cannot enter my answers to the waitlist questions of CIS 505 & 521. Please help resolve the issues. Thanks!

![image](https://user-images.githubusercontent.com/108846109/177672283-da7d0f07-0b89-48ec-a90c-22bf52ebe8ee.png)
![image](https://user-images.githubusercontent.com/108846109/177672309-27e628ef-c87f-41bc-ae5e-2b2b5833dee3.png)

**Comment by devietti** [comment]
Sorry about that, there was an issue with importing PRs from Path. It has been resolved now, so you should be able to answer these questions now. Same root cause as #5.
