### ISSUE TITLE
CIS 630 - How to provide student input

### ISSUE THREAD

**Issue by Manni-Arora** [upenn/cis-waitlist-issues#8]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/77749848/177686200-6674242f-602f-493c-8f81-f4e9f00187ec.png">

**Comment by devietti** [comment]
CIS 6300 was cancelled for Fall 2022, actually. We'll delete the requests in our website. We can't reject the requests on Path because the course is already cancelled, though.
