### ISSUE TITLE
Still could not answer questions of CIS 5050

### ISSUE THREAD

**Issue by Mirrorlene** [upenn/cis-waitlist-issues#9]
Seems that the issue is fixed, but that's not for me. 

Also, the status shows that I've already registered for this course. Do I still need to submit the request?(Path@Penn asks me to do so...)

<img width="1277" alt="微信图片_20220707135313" src="https://user-images.githubusercontent.com/62650455/177838176-2034a395-fe7a-41c9-b28d-b68bd821a7c6.png">

**Comment by devietti** [comment]
If you're already registered then you don't need to complete the questions. Does Path@Penn show you as registered for the course?

**Comment by Mirrorlene** [comment]
> 

Yes. But it also has this. I was confused for quite a long time about my status...
![image](https://user-images.githubusercontent.com/62650455/177868152-367ab0df-7ef7-4dfc-b495-ccd940d4c7e9.png)

**Comment by devietti** [comment]
I see, this "section details" part is part of the information about the course, telling you how to register. But there are a lot of details here, see https://advising.cis.upenn.edu/register/ for more information.

I'll mark this as closed since the waitlist is working as expected.
